FROM nginx:alpine

# Nginx config
COPY docker/nginx-docker.conf /etc/nginx/conf.d/default.conf

# Frontend dosyalari
COPY frontend/ /usr/share/nginx/html/

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=10s --retries=3 \
    CMD wget --no-verbose --tries=1 --spider http://localhost:80/ || exit 1
